#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import pysam

if len(sys.argv) < 2:
    sys.exit('No input')

with pysam.AlignmentFile(sys.argv[1], "rb") as samfile:
    i = 0
    for read in samfile.fetch():
        i += 1
    print(i)
